import pandas as pd

print("\n" + "="*60)
print("FILE 1: mental_health_balanced.csv")
print("="*60)
df1 = pd.read_csv("mental_health_balanced (1).csv")
print(f"Shape:   {df1.shape}")
print(f"Columns: {df1.columns.tolist()}")
print(f"\nNull values:\n{df1.isnull().sum()}")
print(f"\nCondition distribution:\n{df1['condition'].value_counts()}")
print(f"\nText length (words) stats:")
print(df1['text'].str.split().str.len().describe().round(1))

print("\n" + "="*60)
print("FILE 2: cleanData.csv")
print("="*60)
df2 = pd.read_csv("cleanData.csv")
print(f"Shape:   {df2.shape}")
print(f"Columns: {df2.columns.tolist()}")
print(f"\nNull values:\n{df2.isnull().sum()}")
print(f"\nStatus distribution:\n{df2['status'].value_counts()}")
print(f"\nText length (words) stats:")
print(df2['statement'].str.split().str.len().describe().round(1))

print("\n" + "="*60)
print("FILE 3: labeled.csv — salvage audit")
print("="*60)
df3 = pd.read_csv("labeled.csv")
print(f"Shape:   {df3.shape}")
print(f"Columns: {df3.columns.tolist()}")
print(f"\nNull in label: {df3['label'].isna().sum()}")
print(f"Valid labels:  {df3['label'].notna().sum()}")
print(f"\nLabel distribution:\n{df3['label'].value_counts()}")
print(f"\nText length (valid rows only):")
print(df3[df3['label'].notna()]['text'].str.split().str.len().describe().round(1))